run_steps:
  dataset_processing: false
  testing_and_evaluation: false
  adversarial_perturbation: true
  robust_training: false
dataset_name: Demo_dataset
file_name: Combined_dataset0.csv
dataset_processing:
  preprocess: true
  split: true
  split_mode: default
  split_ratio: 0.3
  feature_extraction: true
  feature_extractor: Stat
testing_and_evaluation:
  model: MLP
  model_name: MLP_CH_DoS_stat
  mode: test
  epochs: 5
  train_dataset_dir: CH_DoS_train_stat
  test_dataset_dir: CH_DoS_test_stat
adversarial_perturbation:
  attack_case: mal_to_benign
  adv_attack: PGD
  adv_attack_type: whitebox
  surrogate_model: MLP_CH_DoS_stat.h5
  target_model: null
  epsilon: 5
  offset: 0.1
  eps_step: 0.5
  max_iter: 20
robust_training:
  defense_method: FrameBuilderRetrainer
  adv_samples: 350
  adv_examples_path: null
